get-started/midi-developers/app-developers/docs/consuming-midi-sdk.md, get-started/midi-developers/app-developers/samples/cpp-juce/README.md, get-started/midi-developers/app-developers/samples/flutter/README.md, get-started/midi-developers/app-developers/samples/js-electron/README.md, src/app-dev-sdk/sdk-core-projection-cs/nuget/Microsoft.Devices.Midi2.Core.CS.nuspec, src/app-dev-sdk/sdk-core/MidiAppSdkVersion.h, src/app-dev-sdk/sdk-core/MidiServices.cpp
Added basic documentation and updated versions. More details coming in the actual release.
=> Prep for a developer preview of the SDK Shape

get-started/midi-developers/app-developers/samples/cpp-winrt/sdk-client-basics/main.cpp, get-started/midi-developers/app-developers/samples/cpp-winrt/sdk-client-basics/packages.config, get-started/midi-developers/app-developers/samples/cpp-winrt/sdk-client-basics/sdk-client-basics.vcxproj, get-started/midi-developers/app-developers/samples/csharp-net/sdk-client-basics-cs/Program.cs, get-started/midi-developers/app-developers/samples/csharp-net/sdk-client-basics-cs/sdk-client-basics-cs.csproj, src/app-dev-api/api-core-cpp-winrt-tests/Benchmarks.cpp, src/app-dev-api/api-core-cpp-winrt-tests/BidirectionalEndpointTests.cpp, src/app-dev-api/api-core/IMidiEndpointMessageListener.idl, src/app-dev-api/api-core/IMidiOutputConnection.idl, src/app-dev-api/api-core/MidiBidirectionalEndpointConnection.cpp, src/app-dev-api/api-core/MidiBidirectionalEndpointConnection.h, src/app-dev-api/api-core/MidiOutputEndpointConnection.cpp, src/app-dev-api/api-core/MidiOutputEndpointConnection.h, src/app-dev-api/api-core/MidiSession.cpp, src/app-dev-api/api-core/MidiSession.h, src/app-dev-api/api-core/ump_helpers.h, src/app-dev-sdk/sdk-core-projection-cs/nuget/Microsoft.Devices.Midi2.Core.nuspec, src/app-dev-sdk/sdk-core-projection-cs/nuget/README.md
Renamed some of the send overloads. 
Added code to the message receive callback to make calls to the different listeners (this requires more testing).
Aligns with nuget package preview1 94
=> API and sample updates for core functions

src/api/Abstraction/SimpleLoopbackAbstraction/Midi2.SimpleLoopbackAbstraction.cpp, src/api/Abstraction/SimpleLoopbackAbstraction/MidiLoopbackDevice.cpp, src/api/Client/Midi2Client/MidiBidirectionalEndpointConnection.cpp, src/api/Client/Midi2Client/MidiBidirectionalEndpointConnection.h, src/api/Client/Midi2Client/MidiInputEndpointConnection.cpp, src/api/Client/Midi2Client/MidiInputEndpointConnection.h, src/api/Client/Midi2Client/MidiOutputEndpointConnection.cpp, src/api/Client/Midi2Client/MidiOutputEndpointConnection.h, src/api/Client/Midi2Client/MidiSession.cpp, src/api/Test/Midi2.Api.unittests/UnidirectionalEndpointTests.cpp, src/api/Test/Midi2.Api.unittests/api-core-cpp-winrt-tests.vcxproj, src/api/Test/Midi2.Api.unittests/api-core-cpp-winrt-tests.vcxproj.filters
Note: creation works, but these do not yet pass messages properly, so they fail the loopback test, but pass the creation test.
=> Implementing Input and Output Endpoint Connections

src/api/Abstraction/NetworkMidiAbstraction/Midi2.NetworkMidiEndpointManager.cpp, src/api/Abstraction/NetworkMidiAbstraction/Midi2.NetworkMidiEndpointManager.h, src/api/Abstraction/NetworkMidiAbstraction/pch.h, src/api/Abstraction/VirtualMidiAbstraction/Midi2.VirtualMidiEndpointManager.cpp, src/api/Service/Exe/MidiDeviceManager.cpp
Had forgotten to test with no config file. Tested and fixed.
=> Fix problem where service crashes if no config file present

build/staging/version/BundleInfo.wxi, get-started/midi-developers/app-developers/samples/electron/electron-api-basics/.vscode/launch.json, get-started/midi-developers/app-developers/samples/electron/electron-api-basics/index.html, get-started/midi-developers/app-developers/samples/electron/electron-api-basics/main.js, get-started/midi-developers/app-developers/samples/electron/electron-api-basics/package-lock.json, get-started/midi-developers/app-developers/samples/electron/electron-api-basics/package.json, get-started/midi-developers/app-developers/samples/electron/electron-api-basics/preload.js
The projection is not yet published elsewhere, but will be included in official releases here.
The projection itself is generated using a customized version of NodeRT.
One current limitation is the SendMessageStruct function does not project to Electron. So far, everything else does.
=> Added Electron sample code to Get Started area

build/staging/version/BundleInfo.wxi, get-started/midi-developers/app-developers/samples/cpp-winrt/README.md, get-started/midi-developers/app-developers/samples/cpp-winrt/api-watch-endpoints/PropertySheet.props, get-started/midi-developers/app-developers/samples/cpp-winrt/api-watch-endpoints/api-watch-endpoints-cpp.sln, get-started/midi-developers/app-developers/samples/cpp-winrt/api-watch-endpoints/api-watch-endpoints-cpp.vcxproj, get-started/midi-developers/app-developers/samples/cpp-winrt/api-watch-endpoints/main.cpp, get-started/midi-developers/app-developers/samples/cpp-winrt/api-watch-endpoints/packages.config, get-started/midi-developers/app-developers/samples/cpp-winrt/api-watch-endpoints/pch.cpp, get-started/midi-developers/app-developers/samples/cpp-winrt/api-watch-endpoints/pch.h, src/user-tools/midi-console/Midi/Commands/Clock/TimeCommand.cs, src/user-tools/midi-console/Midi/Commands/Endpoint/MonitorEndpointCommand.cs, src/user-tools/midi-console/Midi/Commands/Watcher/WatchEndpointsCommand.cs, src/user-tools/midi-console/Midi/Program.cs, src/user-tools/midi-console/Midi/Resources/Strings.Designer.cs, src/user-tools/midi-console/Midi/Resources/Strings.resx
The device watcher is the preferred way to enumerate devices, handle plug/unplug, property updates, etc.
=> Added device watcher sample (C++) and device watcher feature to console

build/staging/version/BundleInfo.wxi, src/user-tools/midi-console/Midi/Commands/Endpoint/MonitorEndpointCommand.cs, src/user-tools/midi-console/Midi/Commands/Watcher/WatchEndpointsCommand.cs
=> Fix console missing "E" when escape key pressed #168

src/user-tools/midi-console/Midi/Commands/Endpoint/EndpointMonitorCommand.cs
Fix issue #200 200 with console UI input thread locking up if being spammed with messages
=> Fix issue #200

build/staging/version/BundleInfo.wxi, src/api/Abstraction/MidiSrvAbstraction/Midi2.MidiSrv.cpp, src/api/Libs/MidiKs/MidiKs.cpp, src/user-tools/midi-console/Midi/Commands/Endpoint/EndpointMonitorCommand.cs, src/user-tools/midi-console/Midi/CustomTable/MidiMessageTable.cs
Lower CPU usage, faster message display, etc. The monitoring is now multi-threaded and has done away with the tight loops for the most part.
This may address #182, but I can't yet repro that exact issue at will.
=> Significant console performance updates

build/build.cake, build/staging/version/BundleInfo.wxi, get-started/midi-developers/app-developers/docs/README.md, get-started/midi-developers/app-developers/docs/timestamps.md, src/api/Abstraction/DiagnosticsAbstraction/Midi2.LoopbackMidiBidi.cpp, src/api/Abstraction/DiagnosticsAbstraction/dllmain.cpp, src/api/Abstraction/MidiSrvAbstraction/Midi2.MidiSrv.cpp, src/api/Client/Midi2Client/MidiClock.idl, src/api/Client/Midi2Client/MidiEndpointConnection.cpp, src/api/Client/Midi2Client/MidiEndpointConnection.h, src/api/Libs/MidiXProc/MidiXProc.cpp, src/api/Test/Midi2.Abstraction.unittests/Midi2.Abstraction.unittests.vcxproj, src/api/Test/Midi2.Client.benchmarks/Midi2.Client.benchmarks.vcxproj, src/api/Test/Midi2.Client.unittests/Midi2.Client.unittests.vcxproj, src/api/Test/Midi2.Driver.unittests/Midi2.Driver.unittests.vcxproj, src/api/Test/Midi2.Service.unittests/Midi2.Service.unittests.vcxproj, src/api/Test/Midi2.Transform.unittests/Midi2.Transform.unittests.vcxproj, src/oob-setup/midi-services-setup.sln, src/user-tools/midi-console/Midi/AnsiConsoleOutput.cs, src/user-tools/midi-console/Midi/Commands/Clock/TimeCommand.cs, src/user-tools/midi-console/Midi/Commands/Endpoint/EndpointMonitorCommand.cs, src/user-tools/midi-console/Midi/Commands/Endpoint/EndpointSendMessageCommand.cs, src/user-tools/midi-console/Midi/CustomTable/MidiMessageTable.cs
Fix the dropped messages problem. #227
=> Fix issue 227

get-started/midi-developers/app-developers/samples/csharp-net/app-to-app-midi-cs/MidiSample.AppToAppMidi/Note.cs
=> Update pad controller sample to send better messages

diagnostics/trace-logging/MidiServices.wprp, diagnostics/trace-logging/README.md
Also added a README to explain how to use it.
=> Update trace logging profile to include transforms and all abstractions

src/api/Drivers/USBMIDI2/Driver/Device.cpp
Message not being handled in USB out code and thus hanging.
=> Issue #397 handling of System 0xfd

build/staging/version/BundleInfo.wxi, samples/cpp-winrt/basics/client-basics-cpp.vcxproj, samples/cpp-winrt/basics/packages.config, samples/cpp-winrt/loopback-endpoints/loopback-endpoints-cpp.vcxproj, samples/cpp-winrt/loopback-endpoints/packages.config, samples/cpp-winrt/send-speed/packages.config, samples/cpp-winrt/send-speed/send-speed-cpp.vcxproj, samples/cpp-winrt/static-enum-endpoints/packages.config, samples/cpp-winrt/static-enum-endpoints/static-enum-endpoints-cpp.vcxproj, samples/cpp-winrt/virtual-device-app-winui/packages.config, samples/cpp-winrt/virtual-device-app-winui/virtual-device-app-winui.vcxproj, samples/cpp-winrt/watch-endpoints/packages.config, samples/cpp-winrt/watch-endpoints/watch-endpoints-cpp.vcxproj, src/app-sdk/sdk-runtime-installer/main-bundle/Bundle.wxs
Missed checking this in after build.
=> DP7 build nuget package versions

src/api/Client/WinMM/winmmdrv.cpp, src/api/Inc/MidiDefs.h, src/api/Service/Exe/MidiClientManager.cpp, src/api/Service/Exe/MidiDeviceManager.cpp, src/api/Service/Inc/MidiDeviceManager.h, src/api/Test/Libs/MidiSWEnum/MidiSWEnum.cpp, src/api/Transport/KSAggregateTransport/Midi2.KSAggregateMidiEndpointManager.cpp, src/api/Transport/KSTransport/Midi2.KSMidiEndpointManager.cpp, src/api/Transport/KSTransport/Midi2.KSMidiEndpointManager.h, src/api/idl/WindowsMidiServices.idl
PRing Gary's changes to main for additional testing
=> add winmm ports based on the gtb & fb

src/api/Inc/MidiDefs.h, src/api/Inc/json_defs.h, src/api/Service/Exe/MidiDeviceManager.cpp, src/api/Service/Inc/MidiDeviceManager.h, src/api/Transport/KSAggregateTransport/Midi2.KSAggregateMidiConfigurationManager.cpp, src/api/Transport/KSTransport/Midi2.KSMidiConfigurationManager.cpp
static function blocks, port naming, most of the plumbing for custom port numbers.
=> function block and gtb naming

src/api/Drivers/USBMIDI2/Driver/Device.cpp
Resolved issue where not incrementing processed words when handling SYSEX conversions.
=> numProcessed in SySEX Managment

src/api/Drivers/USBMIDI2/Driver/Device.cpp
Corrected processing to properly remove created memory in error condition. Cleaned up code.
=> Corrected processing to avoid memory leak

src/api/Drivers/USBMIDI2/Driver/Device.cpp
For both write and read USB routines, the processed data was not being advanced in case of invalid cable number. This has been resolved.
=> Advance of processed data pointers in case of dropped packet.

src/api/Drivers/MinMidi/Driver/MidiPin.cpp, src/api/Drivers/MinMidi/Driver/MidiPin.h, src/api/Inc/MidiEndpointCustomProperties.h, src/api/Inc/MidiEndpointMatchCriteria.h, src/api/Libs/MidiPluginConfigurationLib/MidiEndpointCustomPropertiesCache.cpp, src/api/Libs/MidiPluginConfigurationLib/MidiEndpointNameTable.cpp, src/api/Libs/MidiPluginConfigurationLib/MidiPluginConfigurationLib.vcxproj, src/api/Test/Midi2.Transport.unittests/Midi2TransportTests.cpp
fix minmidi incompatibility w/ legacy api, make multiclient test skip if no endpoints are available, fix build and oacr issues in public branch.
=> legacy api Testfixes, and build and oacr fixes

src/api/Libs/MidiPluginConfigurationLib/MidiEndpointNameTable.cpp, src/api/Service/Exe/MidiService.cpp, src/api/Transform/UMPToByteStream/Midi2.UMP2BSMidiTransform.cpp
Fix bug with filtering WinMM groups, and add RedirectionTrust policy
=> WinMM group routing fix and RedirectionTrust policy

src/api/Libs/MidiKs/MidiKs.cpp, src/api/Libs/MidiKsCommon/KsHandleWrapper.cpp, src/api/Service/Exe/MidiClientManager.cpp, src/api/Service/Exe/MidiDeviceManager.cpp, src/api/Service/Exe/MidiDevicePipe.cpp, src/api/Service/Exe/MidiService.cpp, src/api/Service/Exe/MidiSrv.cpp, src/api/Service/Inc/MidiClientManager.h, src/api/Service/Inc/MidiDeviceManager.h, src/api/Service/Inc/MidiPipe.h
Bring surprise removal fixes over from Windows branches
=> Surpriseremoval fixes

docs/assets/css/style.css, src/user-tools/midi-settings/Microsoft.Midi.Settings.Core/Services/FileService.cs, src/user-tools/midi-settings/Microsoft.Midi.Settings/Services/GeneralSettingsService.cs, src/user-tools/midi-settings/Microsoft.Midi.Settings/Views/EndpointsLoopPage.xaml, src/user-tools/midi-settings/Microsoft.Midi.Settings/Views/NetworkMidi2SetupPage.xaml
Fix settings app bugs
Fix documentation table border color
=> Pete dev - Settings app and docs bug fixes
